### ISSUE TITLE
Multilevel support

### ISSUE THREAD

**Issue by lavermil** [1nVitr0/plugin-vscode-blocksort#15] opened 2021-05-27 17:25 UTC
Can you add the support to do multilevel sorts. So you will sort based on the parent like you do today but also have an option to sort the children and any other sub-levels too.

This is very helpful in the world of comparing network device, application configs, etc using diff tools. Sometime as different version come out and they change config files/etc around the order of stuff/etc. Without this python script I have below it is very hard to compare them. 

My method in python I am using allows me to specify what the indent pattern is. For example if you want to use a tab, 2 space, 3 space, 4 spaces, etc. I have also added in python the ability to filter out lines like ! or # or what ever I want as long as it is an exact match.

**Example:**
```
Parent3
!
Parent2
  child1
    child1c
    child1a
    child1b
!
Parent1
  child2
    child2b
      child1a
      child1c
      child1b
    child2a
      child1b
      child1a
      child1c
  child1
```

**Desired:**
```
Parent1
  child1
  child2
    child2a
      child1a
      child1b
      child1c
    child2b
      child1a
      child1b
      child1c
Parent2
  child1
    child1a
    child1b
    child1c
Parent3
```

**Comment by 1nVitr0** [comment] 2021-06-08 14:27
@lavermil Sorry that I took so long to start, The basics are working now. I'll have to check if the custom ignore lines (like `!`) still work and then provide the commands to actually execute the multilevel sort. I reckon the update is live somewhere between today and friday.

**Comment by lavermil** [comment] 2021-06-09 00:01
> > @lavermil As of [v0.5.1 ](https://github.com/1nVitr0/plugin-vscode-blocksort/releases/tag/v0.5.1) Multilevel Sorting is now supported. You can use the commands `Sort Blocks Deep Ascending (Multilevel)` (`blocksort.sortBlocksMultilevelAsc`) and `Sort Blocks Deep Descending (Multilevel)` (`blocksort.sortBlocksMultilevelDesc`).
> > By default it shows a dialog asking for a depth (`-1` is infinite). This can be disabled by setting `blocksort.askForMultilevelDepth` to `false`.
> 
> I just tried it and it works nicely! I have to do a deeper test but so far it works great. I will grab a 1k+ line config and compare.

Sadly there were problem with bigger datasets. I will sanitize data and share so you can have a better dataset to work with.

**Comment by lavermil** [comment] 2021-06-09 00:25
> > > @lavermil As of [v0.5.1 ](https://github.com/1nVitr0/plugin-vscode-blocksort/releases/tag/v0.5.1) Multilevel Sorting is now supported. You can use the commands `Sort Blocks Deep Ascending (Multilevel)` (`blocksort.sortBlocksMultilevelAsc`) and `Sort Blocks Deep Descending (Multilevel)` (`blocksort.sortBlocksMultilevelDesc`).
> > > By default it shows a dialog asking for a depth (`-1` is infinite). This can be disabled by setting `blocksort.askForMultilevelDepth` to `false`.
> > 
> > 
> > I just tried it and it works nicely! I have to do a deeper test but so far it works great. I will grab a 1k+ line config and compare.
> 
> Sadly there were problem with bigger datasets. I will sanitize data and share so you can have a better dataset to work with.

Here is the sample config stuff you can try to sort. I had to attach the file and also provide a pastebin link as well as the code bit is not keeping formatting when including the config inline. :(

https://pastebin.com/TG1Tpb4F
[sample_config.txt](https://github.com/1nVitr0/plugin-vscode-blocksort/files/6620318/sample_config.txt)

**Comment by 1nVitr0** [comment] 2021-06-14 09:10
@lavermil To me the output looks ok. Do you mean port `443` being sorted *before* port `80`?

This is due to string sorting, as `4` is a lower value than `8`, thus being moved to the front. I can add an option that parses numbers and sorts them in a more intuitive manner. Although it will most likely be an option that is disabled by default as it will take considerably more time to sort on large documents.

**Comment by 1nVitr0** [comment] 2021-06-14 12:21
@lavermil If the problem was due to non-intuitive sorting of numbers, there is an option for "Natural Sorting" as of version [v0.6.0](https://github.com/1nVitr0/plugin-vscode-blocksort/releases/tag/v0.6.0). Setting `blocksort.enableNaturalSorting` to true will enable it, additional options can be set using `blocksort.naturalSorting`. The most important one is `blocksort.naturalSorting.padding`, which controls the maximum length to which numbers will be sorted naturally (no more than 16 due to the rounding behaviour of JavaScript floats).

**Comment by 1nVitr0** [comment] 2021-06-14 15:00
Will close the issue for now, if the problem is something else just shoot me a messahe

**Closed by 1nVitr0** 2021-06-14 15:00 UTC
Labels: enhancement

**Comment by lavermil** [comment] 2021-06-18 22:04
> Will close the issue for now, if the problem is something else just shoot me a message

I have enabled the sort naturally and it is a perfect fit! Thank you so much for getting this done and done so quickly!!!!
